MediaShare.Web/Controllers/AllFilesController.cs
namespace MediaShare.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using PagedList;
    using AutoMapper.QueryableExtensions;

    using MediaShare.Data;
    using MediaShare.Models;
    using MediaShare.Web.Models;
    using MediaShare.Web.Models.Files;

    public class AllFilesController : BaseController
    {
        private const int PageSize = 5;

        public AllFilesController(IMediaShareData data)
            : base(data)
        {

        }

        // GET: AllFiles
        public ActionResult Index()
        {
            var videos = this.MediaFiles.Project().To<AdvancedMediaFileViewModel>().OrderByDescending(f => f.DateCreated);

            this.IsSameInSession("type", "Both");
            this.IsSameInSession("searchString", string.Empty);
            return this.View(videos.ToPagedList(1, PageSize));
        }

        [HttpGet]
        public ActionResult RenderFiles(int? page, FilterViewModel filter)
        {
            var allFiles = this.MediaFiles.Project().To<AdvancedMediaFileViewModel>();
            
            if (!this.IsSameInSession("type", filter.Type))
            {
                allFiles = this.Filter(allFiles, filter.Type);
            }
                
            if (!this.IsSameInSession("searchString", filter.SearchString))
            {
                allFiles = allFiles.Where(s => s.Title.ToUpper()
                        .Contains(filter.SearchString != null ? filter.SearchString.ToUpper() : string.Empty));
            }
            
            allFiles = this.Sort(allFiles, filter.OrderBy, filter.SortType);
            
            

            return this.PartialView("_PagedFiles", allFiles.ToPagedList(page ?? 1, PageSize));
        }

        private IQueryable<AdvancedMediaFileViewModel> Filter(IQueryable<AdvancedMediaFileViewModel> files, string filterType)
        {           
            if (filterType == "Video")
            {
                return files.Where(s => s.Type == MediaType.Video);
            }

            if (filterType == "Audio")
            {
                return files.Where(s => s.Type == MediaType.Audio);
            }

            return files;
        }

        private IQueryable<AdvancedMediaFileViewModel> Sort(IQueryable<AdvancedMediaFileViewModel> files, string orderBy, string sortType)
        {

            switch (orderBy)
            {
                case "Views":
                    {
                        if (sortType == "Ascending")
                        {
                            return files.OrderBy(f => f.ViewsCount);
                        }
                        else
                        {
                            return  files.OrderByDescending(f => f.ViewsCount);
                        }
                    }
                case "Rating":
                    {
                        if (sortType == "Ascending")
                        {
                            return files.OrderBy(f => (double)f.Votes.Sum(v => v.Value) / f.Votes.Count);
                        }
                        else
                        {
                            return files.OrderByDescending(f => (double)f.Votes.Sum(v => v.Value) / f.Votes.Count);
                        }
                    }
                default:
                    {
                        if (sortType == "Ascending")
                        {
                            return files.OrderBy(f => f.DateCreated);
                        }
                        else
                        {
                            return files.OrderByDescending(f => f.DateCreated);
                        }
                    }
            }
        }

        private bool IsSameInSession(string key, string value)
        {
            value = value ?? (this.Session[key] != null ? this.Session[key].ToString() : null);
            if (this.Session[key] != null && this.Session[key].ToString() == value)
            {
                return true;
            }

            this.Session[key] = value;
            return false;
        }

        private void ResetSession(params string[] keys)
        {
            foreach (var key in keys)
            {
                this.Session[key] = null;
            }
        }
    }
}

MediaShare.Web/Controllers/LatestFilesController.cs
namespace MediaShare.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using MediaShare.Data;
    using MediaShare.Web.Models.Files;
    using MediaShare.Models;

    public class LatestFilesController : BaseController
    {
        public LatestFilesController(IMediaShareData data) : base(data)
        {
        }

        // GET: LatestFiles
        public ActionResult Index()
        {
            var files = this.MediaFiles.Project().To<BasicMediaFileViewModel>();
            return this.View(files);
        }
    }
}

MediaShare.Web/Controllers/ThumbnailController.cs
using System.Security.Principal;
using MediaShare.Data;
using MediaShare.Web.Areas.Authorized.Controllers;
using MediaShare.Web.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediaShare.Models;

namespace MediaShare.Web.Controllers
{
    public class ThumbnailController : BaseController
    {
        public ThumbnailController(IMediaShareData data) : base(data)
        {
        }
        
        // GET: Thumbnail
        public ActionResult Index(int id)
        {
            var file = this.MediaFiles.FirstOrDefault(x => x.Id == id);
            if (file.Type == MediaType.Video)
            {
                ViewBag.ThumbLink = DropboxHandler.GetUrl(file.Thumbnail);
            }
            else
            {
                 ViewBag.ThumbLink = DropboxHandler.GetUrl("Audio Symbol.png");
            }
            return PartialView(id);
        }
    }
}

MediaShare.Web/Views/Shared/_FilePartial.cshtml
@using MediaShare.Web.Models.Files;

@model BasicMediaFileViewModel

@Html.DisplayFor(f => f.Title, "DisplayMediaTitle", new { id = @Model.Id })
@{
    Html.RenderAction("Index", "Thumbnail", new { id = @Model.Id, area = "" });
}

MediaShare.Web/Views/Shared/_Layout.cshtml
@using MediaShare.Common;

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title </title>
        <meta property="og:image" content="@ViewBag.ThumbLink" />
        <meta property="og:video" content="@ViewBag.MediaLink" />
        <meta property="og:video:height" content="200" />
        <meta property="og:video:width" content="300" />
        <meta property="og:video:type" content="video/webm" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("styles", required: false)
        <meta name="description" content="Media files sharing" />
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MediaShare", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Search", "Index", "AllFiles", new { area = "" }, new { })</li>
                        <li>@Html.ActionLink("Latest", "Index", "LatestFiles", new { area = "" }, new { })</li>

                        @if (Request.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    Upload <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Upload Video clip", "VideoIndex", "UploadFile", new { area = "Authorized" }, new { })</li>
                                    <li>@Html.ActionLink("Upload Song", "AudioIndex", "UploadFile", new { area = "Authorized" }, new { })</li>
                                </ul>
                            </li>
                        }
                        
                        @if (User.IsInRole(GlobalConstants.Admin))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    Administration <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Files", "Index", "FilesAdministration", new { area = "Admin" }, new { })</li>
                                    <li>@Html.ActionLink("Comments", "Index", "CommentsAdministration", new { area = "Admin" }, new { })</li>
                                    <li>@Html.ActionLink("Users", "Index", "UsersAdministration", new { area = "Admin" }, new { })</li>
                                </ul>
                            </li>
                        }

                    </ul>

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer class="text-center">
                <p>&copy; @DateTime.Now.Year - MediaShare</p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("scripts", required: false)
    </body>
</html>
    

MediaShare.Web/Views/Shared/_PagedFiles.cshtml
@using MediaShare.Web.Models.Files

@model PagedList.IPagedList<BasicMediaFileViewModel>

@if (Model.Any())
{

    if (Request.IsAjaxRequest() || ViewBag.Title == "All Media")
    {
        @Html.DisplayFor(m => Model, "DisplayAsyncPager", new { action = "RenderFiles", controller = "AllFiles" })
    }
    <div class="col-md-12" id="Loader" style="display:none">
        <span style="color:#00ffff">
            Loading...Please wait
            <img src="~/MediaFiles/red loader.gif" width="50" height="50" alt="Alternate Text" />
        </span>
    </div>
    foreach (var item in Model)
    {
        var someClass = "col-md-4";
        if (ViewBag.Title == "All Media" || Request.IsAjaxRequest())
        {
            someClass = "col-md-7";
        }

        <div class=@someClass style="margin-bottom:50px;">
            @{Html.RenderPartial("_FilePartial", item);}
            @if (ViewBag.Title == "All Media" || Request.IsAjaxRequest())
            {
                Html.RenderPartial("FileInfoPartial", item);                          
            }
        </div>
    }
    if (Request.IsAjaxRequest() || ViewBag.Title == "All Media")
    {
        @Html.DisplayFor(m => Model, "DisplayAsyncPager", new { action = "RenderFiles", controller = "AllFiles" })
    }
}
else
{
    <h3 class="pull-left">No Entries...</h3>
}