MediaShare.Web/Controllers/FileDetailsController.cs
namespace MediaShare.Web.Controllers
{
    using System.Linq;
    using System.Security.Principal;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using AutoMapper.QueryableExtensions;
    using MediaShare.Data;
    using MediaShare.Models;
    using MediaShare.Web.Models;	
    using MediaShare.Web.Models.Files;
    using MediaShare.Web.Infrastructure.Helpers;
    using System.Net;
    using System.Threading.Tasks;
    using System;

    public class FileDetailsController : BaseController
    {
        private readonly IIdentity identity;

        public FileDetailsController(IMediaShareData data, IIdentity identity) : base(data)
        {
            this.identity = identity;
        }

        // GET: MediaFileDetails
        public ActionResult Details(int? id)
        {
            var currentUser = this.identity.GetUserId();
            if (currentUser != null)
            {
                this.ViewBag.IsFavourited = this.Data.Users.Find(currentUser).Favourites.Any(f => f.Id == id);
            }
            else
            {
                this.ViewBag.IsFavourited = false;
            }

            if (id == null)
            {
                return this.RedirectToAction("Index", "Home");
            }
            var file = this.MediaFiles.Project().To<MediaFileViewModel>()
                           .FirstOrDefault(f => f.Id == id);
            
         
            ViewBag.MediaLink = DropboxHandler.GetUrl(file.Content);
			if (file.Type == MediaType.Video)
            {			
				ViewBag.ThumbLink = DropboxHandler.GetUrl(file.Thumbnail);
               
            }else
			{
			    ViewBag.ThumbLink = DropboxHandler.GetUrl("Audio Symbol.png");
			}
            if (file.AuthorId == currentUser)
            {
                this.ViewBag.IsYours = true;
            }
            else
            {
                this.ViewBag.IsYours = false;
            }

            return this.View(file);
        }

        // GET: Votes
        public ActionResult FileVotes(int id)
        {
            var file = this.MediaFiles.Project().To<MediaFileViewModel>()
                           .FirstOrDefault(f => f.Id == id);
            return this.PartialView(file);
        }

        public ActionResult FileComments(int id)
        {
            var comments = this.MediaFiles.Project().To<MediaFileViewModel>()
                               .FirstOrDefault(f => f.Id == id).Comments.AsQueryable()
                               .Project().To<CommentViewModel>().OrderByDescending(c => c.DateCreated)
                               .ToList();
            return this.PartialView(comments);
        }

        public void IncreaseViewCount(int id)
        {
            this.MediaFiles.FirstOrDefault(f => f.Id == id).ViewsCount++;
            this.Data.SaveChanges();
        }
    }
}

MediaShare.Web/Views/Shared/DisplayTemplates/CustomDate.cshtml
@model DateTime


<p>
    <b>Date Created: </b>
    <span class="latest-files-view-date">
        @Model.ToString("d MMM yyyy", System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))
        at @Model.ToString("hh:mm", System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))
    </span>
</p>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayAsyncPager.cshtml
@using MediaShare.Web.Models.Files;
@using PagedList.Mvc

@model PagedList.IPagedList<BasicMediaFileViewModel>
@{
    string action=ViewData["action"].ToString();
    string controller = ViewData["controller"].ToString();
}  

<div class="col-md-10">
    @Html.PagedListPager(Model, page => Url.Action(action, controller, new { page = page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.OnlyShowFivePagesAtATime, new AjaxOptions { UpdateTargetId = "files-container", LoadingElementId = "Loader", HttpMethod = "GET" }))
</div>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayAuthor.cshtml
@using MediaShare.Web.Areas.Authorized.Models;
@using MediaShare.Common;
@model UserViewModel

<p>
    <b>Created by:  @Html.ActionLink(@Model.Email.ExtractUsernameFromMail(), "Files", "UserFiles", new { area = "Authorized", Id = Model.Id }, new { })</b>
</p>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayFavButtons.cshtml
@model int


<div>
    @Ajax.ActionLink("Add to favourites", "AddFavourites", "DetailsAuthorized", new { area = "Authorized", Id = @Model }, new AjaxOptions { OnSuccess = "hideAddFavBtn", HttpMethod = "Post" }, new { @class = "btn btn-info btn-sm", id = "add-fav-btn", style = ViewData["add"] })
    @Ajax.ActionLink("Remove from favourites", "RemoveFavourites", "DetailsAuthorized", new { area = "Authorized", Id = @Model }, new AjaxOptions { OnComplete = "hideRemFavBtn", HttpMethod = "Post" }, new { @class = "btn btn-warning btn-sm", id = "rem-fav-btn", style=ViewData["rem"] })
</div>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayMediaTitle.cshtml
@model string

@{
    string id = this.ViewData["id"] != null ? this.ViewData["id"].ToString() : null;  
}

<h4 style="font-weight:bold">
    <a href="@Url.Action("Details", "FileDetails", new {area="", Id = id })">
        @Model
    </a>
</h4>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayMediaType.cshtml
@using MediaShare.Models;

@model MediaType

<p>
    <b>Type: </b><span style="color:ButtonShadow">@Model</span>
</p>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayPageHeader.cshtml
@model string
<h3 style="color:azure "><b>@Model</b></h3>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayRate.cshtml
@using MediaShare.Models;

@model ICollection<Vote>
<p>
    <b >Rating: </b><span style="color:ButtonShadow">@(string.Format("{0:0.0}", (double)Model.Sum(x => x.Value) / (Model.Count == 0 ? 1 : Model.Count))) / 5 (@Model.Count user(s) voted)</span> 
</p>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplaySyncPager.cshtml
@using MediaShare.Web.Models.Files;
@using PagedList.Mvc

@model PagedList.IPagedList<BasicMediaFileViewModel>
@{
    string action = ViewData["action"].ToString();
    string controller = ViewData["controller"].ToString();
    string area = ViewData["area"] == null ? "" : ViewData["area"].ToString();
    string id = ViewData["id"].ToString();
}

<div class="col-md-10">
    @Html.PagedListPager(Model, page => Url.Action(action, controller,
                        new { area = area, Id = id, page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
</div>

MediaShare.Web/Views/Shared/DisplayTemplates/DisplayViewsCount.cshtml
@model int

<p>
    <b>Viewed: </b><span style="color:ButtonShadow">@Model time(s)</span>
</p>